config/routes.rb
Rails.application.routes.draw do

  resources :articles, only: [:index, :show, :new, :create, :destroy]
  resources :keywords, only: [:index, :show, :new, :create, :destroy]
  resources :actions, only: [] do
    member do
      post :like
      post :dislike
    end
  end

  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_keywords
  has_many :keywords, through: :article_keywords

  scope :with_keywords, ->(keyword_ids) { joins(:keywords).where(keywords: {id: keyword_ids}) }
  scope :sort_by_score, ->{order(score: :desc)}

  def associate_with_keywords
    service = SetArticleKeywords.new({article: self})
    service.create_keyword_associations!
  end

  def in_black_list?
    self.keywords.pluck(:word_type).include?("black_list")
  end

  def in_white_list?
    self.keywords.pluck(:word_type).include?("white_list")
  end


  def entries_count_of_keyword(keyword)
    self.article_keywords.where(keyword: keyword).first.entries_count
  end

end

app/models/article_keyword.rb
class ArticleKeyword < ActiveRecord::Base
  belongs_to :article
  belongs_to :keyword
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  enum word_type: [ :white_list, :black_list ]

  has_many :article_keywords
  has_many :articles, through: :article_keywords

  def associate_with_keywords
    service = SetArticleKeywords.new({keyword: self})
    service.create_article_associations!
  end

  def increment_rating!
    self.update(score: self.score + 1 )
  end

  def decrement_rating!
    self.update(score: self.score - 1 )
  end
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  before_action :_set_article, :_set_keywords

  def like
    service = ActionService.new(@keywords)
    service.like
    render json: {success: true}
  end

  def dislike
    service = ActionService.new(@keywords)
    service.dislike
    render json: {success: true}
  end

  private

  def _set_article
    @article = Article.where(id: params[:id]).first
  end

  def _set_keywords
    @keywords = @article.keywords
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :_set_article, only: [:show]

  def index
    @articles = Article.includes(:keywords).sort_by_score
    respond_to do |format|
      format.html { }
      format.js { render layout: false }
    end
  end

  def show

  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end


  private

  def _set_article
    @article = Article.where(id: params[:id]).first
  end

  def article_params
    params.require(:article).permit(:title, :author, :content)
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :_set_keyword, only: [:destroy]
  def index
    @keywords = Keyword.all
  end

  def new
    @keyword = Keyword.new
  end

  def create
    @keyword = Keyword.new(keyword_params)
    if @keyword.save
      redirect_to keywords_path
    else
      render :new
    end
  end

  def destroy
    @keyword.destroy
    redirect_to keywords_path
  end

  private

  def _set_keyword
    @keyword = Keyword.where(id: params[:id]).first
  end

  def keyword_params
    params.require(:keyword).permit(:title, :word_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def black_list?(article)
    if article.in_black_list?
    "<p class='article-from-black-list'>Black list</p>"
    else
      ""
    end

  end

  def white_list?(article)
    if article.in_white_list?
    "<p class='article-from-white-list'>White list</p>"
    else
      ""
    end

  end

end

app/views/articles/_article.html.erb
<div class="article_<%=article.id%>">
  <h2 class="article-post"><%= article.title%></h2>
  <p class="article-post-meta"><%= article.created_at%> by <b><%= article.author%></b></p>
  <p class="article-score">
    Score: <%= article.score%>
  </p>
  <%= link_to "Like", "#", class: "btn btn-success like-button", "data-value" => article.id %>
  <%= link_to "Dislike", "#", class: "btn btn-danger dislike-button", "data-value" => article.id %>

  <%= black_list?(article).html_safe %>
  <%= white_list?(article).html_safe %>

  <hr>
  <p><%= link_to "Show", article_path(article)%></p>
</div>

app/views/articles/_article_table.html.erb
<div class="article_<%=article.id%>">
  <h2 class="article-post"><%= article.title%></h2>
  <p class="blog-post-meta"><%= article.created_at%> by <a href="#"><%= article.author%></a></p>
  <hr>
  <p><%= link_to "Show", article_path(article)%></p>
</div>

app/views/articles/_form.html.erb
<%= form_for @article do |form| %>
    Title: <%= form.text_field :title %>
    Author: <%= form.text_field :author %>
    Content: <%= form.text_area :content %>

    <%= form.submit "Save" %>
<%end%>

app/views/articles/index.html.erb
<div class="feed_header">
  <div class="container">
    <h1 class="feed-title">Feed</h1>
    <p class="lead feed-description">Feed Description.</p>
  </div>
</div>

<div class="container" >

  <%= link_to "New Article", new_article_path, class: "btn btn-success"%>

  <div class="row" id="articles-grid">

      <%= render partial: 'article', collection: @articles, as: "article" %>
  </div>

</div>

app/views/articles/index.js.erb
$("#articles-grid").html("<%= escape_javascript( render partial: 'article', collection: @articles, as: "article" ) %>");

app/views/articles/show.html.erb
<div class="container">
  <div class="title">
    Title:
    <%= @article.title%>
  </div>
  <div class="author">
    Author:
    <%= @article.author%>
  </div>

  <div class="content">

    <%= @article.content%>
  </div>
</div>

app/views/keywords/_form.html.erb
<%= form_for @keyword do |form| %>
    Title: <%= form.text_field :title %>
    Word Type: <%= form.select :word_type, collection: Keyword.word_types.keys.to_a %>

    <%= form.submit "Save", class: "btn btn-success" %>
<%end%>

app/views/keywords/_keyword.html.erb
<div class="row keyword" data="<%=keyword.id%>">

  <div class="col-md-4">
    <%= keyword.title%>
  </div>
  <div class="col-md-4">
    <%= keyword.word_type%>
  </div>
  <div class="col-md-4">
    <%= link_to "Delete", keyword_path(keyword), method: :delete, class: "btn btn-danger"%>
  </div>
</div>

app/views/keywords/index.html.erb
<div class="container" >

  <%= link_to "New Keyword", new_keyword_path, class: "btn btn-success"%>

  <div class="row">

    <%= render partial: 'keyword', collection: @keywords, as: "keyword" %>
  </div>

</div>

app/views/keywords/new.html.erb
<div class="container">
  <%= render partial: "form" %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
    </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to 'Feed', root_path%>
          </li>
          <li>
            <%= link_to 'Keywords', keywords_path %>
          </li>


        </ul>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleFeed</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>